logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: default
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: default
      filename: radio_bot.log
      maxBytes: 5242880
      backupCount: 3
      encoding: utf8
  root:
    level: INFO
    handlers:
    - console
    - file
ffmpeg_settings:
  loglevel: error
  codec: copy
  headers:
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
      like Gecko) Chrome/138.0.0.0 Safari/537.36
whisper_model: base
recording_chunk_duration_seconds: 300
max_concurrent_transcriptions: 2
recording_retries: 3
recording_retry_delay_seconds: 60
paths:
  recordings: ./audio_to_process
  transcriptions: ./transcriptions
  hits_file: ./CONTEST_HITS.txt
radio_stations:
- name: 104.5 Fresh Radio (Cornwall)
  stream_url: https://corus.leanstream.co/CFLGFM?args=web_01&startTime={timestamp}
- name: Boom 97.3 (Toronto)
  stream_url: https://corus.leanstream.co/CIUXFM_HIGH?args=web_01
  enabled: false
  headers:
    Referer: https://boom973.com/
- name: 98.1 CHFI (Toronto)
  stream_url: https://rogers.leanstream.co/CHFI-FM
  enabled: false
  headers:
    Referer: https://www.chfi.com/
- name: Z103.5 (Toronto)
  stream_url: http://ice10.securenetsystems.net/CIDC
  enabled: false
- name: Virgin Radio 99.9 (Toronto)
  stream_url: https://live.leanstream.co/CFTR-FM
  enabled: false
  headers:
    Referer: https://www.iheartradio.ca/virginradio/toronto
keywords:
- contest
- giveaway
- raffle
- sweepstakes
- grand prize
- chance to win
- prize
- win
- winner
- won
- claim
- free
- cash
- money
- tickets
- backstage pass
- trip
- vacation
- gift card
- call now
- caller number
- call in
- text to
- text the keyword
- keyword
- cue to call
- secret sound
- website
- .com
- .ca
- dot com
- dot ca
- visit our website
- enter online
- app
- facebook
- instagram
- twitter
